name: Self-hosted-runner
on: 
  push:
    branches: [master]
  
jobs:
  build: 
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setting up node
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}
    - run: npm i
    - run: npm run build --if-present
    - run: npm test